# Generated by Django 4.1.1 on 2022-09-29 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(default='0', max_length=2)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField(default=6)),
                ('occupied_seats', models.IntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.table')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='None', max_length=30)),
                ('Booking_time', models.DateTimeField(unique=True)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.restaurant')),
            ],
        ),
    ]
